title: The Fury Saga Universe
author: J.C. Johnson

description: Official website for The Fury Saga, a supernatural horror thriller series by J.C. Johnson. A prophecy bound to blood and steel refuses to stay buried.

url: "https://johnson8310.github.io"
baseurl: "/The_Fury_Saga_Universe"

markdown: kramdown
